# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)


# make sure to set these in your ~/.zshrc or bash
# ENV["SPACESHIP_2FA_SMS_DEFAULT_PHONE_NUMBER"]
# ENV["FASTLANE_USER"] 
# ENV["FASTLANE_PASSWORD"]
# ENV["FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD"]

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do

    api_key = app_store_connect_api_key(
    key_id: "R2263845L3",
    issuer_id: "69a6de78-cc01-47e3-e053-5b8c7c11a4d1",
    key_filepath: File.join(Dir.pwd, "AuthKey_iOS_nid.p8"),
    duration: 1200, # optional (maximum 1200)
    in_house: false # optional but may be required if using match/sigh
  )

  # pilot(api_key: api_key)


    increment_build_number(xcodeproj: "NeuroidReactnativeSdkExample.xcodeproj")

    get_certificates( # Create or get certificate, and install it
      output_path: "./builds" # Download certificate in the build folder (you don't need to create the folder)
    )
    get_provisioning_profile( # Create or get provisioning profile
      output_path: "./builds",  # Download provisioning profile in the build folder
      filename: "provisioning.mobileprovision" # Rename the local provisioning profile
    )
    update_project_provisioning( # Set the project provisioning profile (related in Xcode to the General > Signing Release section)
      xcodeproj: "NeuroidReactnativeSdkExample.xcodeproj",
      target_filter: "NeuroidReactnativeSdkExample", # Name of your project
      profile: "./builds/provisioning.mobileprovision",
      build_configuration: "Debug"
    )
    update_project_team( # Set the right team on your project
      teamid: CredentialsManager::AppfileConfig.try_fetch_value(:team_id)
    )

    build_app(workspace: "NeuroidReactnativeSdkExample.xcworkspace", scheme: "NeuroidReactnativeSdkExample")
    upload_to_testflight
  end
  
  desc "Push a new beta build to TestFlight"
  lane :testflight_beta do
    
    create_keychain(
    path: "/Users/runner/Library/Keychains/Library/Keychains/signing_temp.keychain-db",
    password: ENV["KEYCHAIN_PASSWORD"],
    default_keychain: true,
    unlock: true,
    timeout: 0,
    lock_when_sleeps: false,
    add_to_search_list: true,
    )
    
    api_key = app_store_connect_api_key(
    key_id: "R2263845L3",
    issuer_id: "69a6de78-cc01-47e3-e053-5b8c7c11a4d1",
    #key_filepath: File.join(Dir.pwd, "Key"),
    key_content: ENV["APP_STORE_API_KEY"],
    is_key_content_base64: true,
    duration: 1200, # optional (maximum 1200)
    in_house: false # optional but may be required if using match/sigh
    )

  # pilot(api_key: api_key)
    app_identifier = CredentialsManager::AppfileConfig.try_fetch_value(:app_identifier)
    api_key = api_key
    current_version = get_version_number(
    target: "NeuroidReactnativeSdkExample" # replace with your main target, required if you have more than one non-test target
    )
    
    latest_build_number = latest_testflight_build_number(
    api_key: api_key,
    version: current_version,
    app_identifier: app_identifier
    )
    
    increment_build_number(
    build_number: (latest_build_number + 3),
    )
    
    import_certificate(
     certificate_path: "/Users/runner/work/neuroid-reactnative-sdk/neuroid-reactnative-sdk/neuroid-ios-sdk/builds/86WM633ZCM.p12",
     certificate_password: ENV["CERTIFICATE_PASSWORD"] || "default",
     keychain_path: "/Users/runner/Library/Keychains/Library/Keychains/signing_temp.keychain-db",
     keychain_password: ENV["KEYCHAIN_PASSWORD"],  
    )
    import_certificate(
     certificate_path: "/Users/runner/work/neuroid-reactnative-sdk/neuroid-reactnative-sdk/neuroid-ios-sdk/builds/86WM633ZCM.cer",
     certificate_password: ENV["CERTIFICATE_PASSWORD"] || "default",
     keychain_path: "/Users/runner/Library/Keychains/Library/Keychains/signing_temp.keychain-db",
     keychain_password: ENV["KEYCHAIN_PASSWORD"],  
    )
    cert(
     api_key: api_key,
     keychain_password: ENV["KEYCHAIN_PASSWORD"],
     keychain_path: "/Users/runner/Library/Keychains/Library/Keychains/signing_temp.keychain-db", # the path to the keychain where your certificates are stored
    )
    
    sigh(
    api_key: api_key,
    app_identifier: app_identifier,
    provisioning_name: "com.example.neuroidreactnativesdk",
    filename: "provisioning.mobileprovision",
    force: true # always recreate this exact profile to ensure it's valid and not expired
    )
    
    profile_name = "com.example.neuroidreactnativesdk" # the name of the profile to use for the build
    output_name = "Neuro ID RN" # specify the name of the .ipa file to generate
    export_method = "app-store" # specify the export method
    compile_bitcode = false # specify whether to enable bitcode
 
    # turn off automatic signing during build so correct code signing identity is guaranteed to be used
    update_code_signing_settings(
    use_automatic_signing: false,
    targets: ["NeuroidReactnativeSdkExample"], # specify which targets to update code signing settings for
    code_sign_identity: "Apple Distribution", # replace with name of code signing identity if different
    bundle_identifier: app_identifier,
    profile_name: profile_name,
    build_configurations: ["Debug"] # only toggle code signing settings for Release configurations
    )
 
    # build the app
    gym(
     scheme: "NeuroidReactnativeSdkExample", # replace with name of your project’s scheme
     output_name: output_name,
     configuration: "Debug",
     export_options: {
      method: export_method,
      provisioningProfiles: {
        app_identifier => profile_name
      },
      compileBitcode: compile_bitcode,
      clean: true,
     }
    )
    
    deliver(
     api_key: api_key,
     skip_screenshots: true,
     skip_metadata: true,
     skip_app_version_update: true,
     force: true, # skips verification of HTML preview file (since this will be run from a CI machine)
     run_precheck_before_submit: false # not supported through ASC API yet
    )
    delete_keychain(keychain_path: "/Users/runner/Library/Keychains/Library/Keychains/signing_temp.keychain-db")
  end
end
