# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)


# make sure to set these in your ~/.zshrc or bash
# ENV["SPACESHIP_2FA_SMS_DEFAULT_PHONE_NUMBER"]
# ENV["FASTLANE_USER"] 
# ENV["FASTLANE_PASSWORD"]
# ENV["FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD"]

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    increment_build_number(xcodeproj: "NeuroidReactnativeSdkExample.xcodeproj")

    get_certificates( # Create or get certificate, and install it
      output_path: "./builds" # Download certificate in the build folder (you don't need to create the folder)
    )
    get_provisioning_profile( # Create or get provisioning profile
      output_path: "./builds",  # Download provisioning profile in the build folder
      filename: "provisioning.mobileprovision" # Rename the local provisioning profile
    )
    update_project_provisioning( # Set the project provisioning profile (related in Xcode to the General > Signing Release section)
      xcodeproj: "NeuroidReactnativeSdkExample.xcodeproj",
      target_filter: "NeuroidReactnativeSdkExample", # Name of your project
      profile: "./builds/provisioning.mobileprovision",
      build_configuration: "Debug"
    )
    update_project_team( # Set the right team on your project
      teamid: CredentialsManager::AppfileConfig.try_fetch_value(:team_id)
    )

    build_app(workspace: "NeuroidReactnativeSdkExample.xcworkspace", scheme: "NeuroidReactnativeSdkExample")
    upload_to_testflight
  end
end
