# ******************************************************************
# This workflow will trigger once a PR opens to main
# ******************************************************************

name: SDK Build and Testing

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v4
        with:
          node-version: '24.x'

      - name: Install dependencies
        run: yarn install

      - name: Typecheck
        run: yarn typecheck

      # TODO: Add back linting check once we fix all linting errors
      # - name: Lint
      #   run: yarn lint

      # TODO: Add back formatting check once we fix all formatting errors
      # - name: Format
      #   run: yarn format --check

      - name: Validate published contents
        run: npm pack --dry-run

  android:
    name: android build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      # Setup .npmrc file to run npm update
      - uses: actions/setup-node@v4
        with:
          node-version: '24.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: yarn install

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin

      - name: Cache Gradle and wrapper
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build android
        working-directory: android
        run: |
          chmod +x gradlew
          ./gradlew build
