name: Publish to npm

on:
  workflow_dispatch:
    
jobs:
  publish_npm_package:
    name: Publish npm package
    runs-on: ubuntu-latest
    steps:
      - name: Main branch checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Publish to npm
        run: |
          git config --global user.email developer@neuro-id.com
          git config --global user.name neuroid-developer
          npm publish --tag latest --dry-run
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
