# ******************************************************************
# To create an NPM package release PR, run this workflow from the GitHub UI and
# select parameters based on the type of release:
#
# - Major Update
#   Select "Branch: main"
#   Set `true` if there are breaking changes affecting sdk's across platforms i.e. react-native, android, ios etc.
#
# - Minor Update 
#   Select "Branch: main"
#   Set `true` if there are multiple minor changes affecting sdk's across platforms i.e. react-native, android, ios etc.
#
# - Patch Update
#   Select "Branch: main"
#   Set `true` if the change affects only the react-native platform.
# ******************************************************************

name: Create version update release PR

on:
  workflow_dispatch:
    inputs:
      version_update:
        description: 'Version Update Type'
        required: true
        default: 'patch'
        type: choice
        options:
        - major
        - minor
        - patch
      major_description:
        description: 'Select major for cross platform breaking changes'
        required: false
        default: 'Select major for cross platform breaking changes'
      minor_description:
        description: 'Select minor for multiple minor cross platform changes'
        required: false
        default: 'Select minor for multiple minor cross platform changes'
      patch_description:
        description: 'Select patch if change only affects this platform'
        required: false
        default: 'Select patch if change only affects this platform'

jobs:
  update_version:
    name: Update package version
    runs-on: ubuntu-latest
    steps:
      - name: Determine update type
        run: |
          echo "RELEASE_TYPE=${{ inputs.version_update}}" >> $GITHUB_ENV

      - name: Main branch checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update version
        run: |
          git config --global user.email developer@neuro-id.com
          git config --global user.name neuroid-developer
          npm version ${{ env.RELEASE_TYPE }}

      - name: Read package version
        run: |
          PACKAGE_VERSION=$(node -p "require('./package.json').version")
          echo "PACKAGE_VERSION=${PACKAGE_VERSION}" >> $GITHUB_ENV
          echo "BRANCH_NAME=releases/${PACKAGE_VERSION}_version_update" >> $GITHUB_ENV
      
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: update package version to ${PACKAGE_VERSION}
          title: Update version
          branch: ${{ env.BRANCH_NAME }}


