# ******************************************************************
# This workflow will trigger once a PR opens to main
# ******************************************************************

name: SDK Testing

on:
  pull_request:
    branches:
      - main

permissions:
  pull-requests: write
  contents: write
  issues: write

jobs:
  buildSdk:
    name: android build
    runs-on: ubuntu-latest

    steps:
      - name: current commit checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.head_ref }}

      # Setup .npmrc file to run npm update
      - uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm install

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: 11
          distribution: temurin

      - name: Cache Gradle and wrapper
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build android
        working-directory: android
        run: |
          chmod +x gradlew
          ./gradlew build --debug

  updateSdk:
    name: npm build
    runs-on: ubuntu-latest

    steps:
      - name: current commit checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.head_ref }}

      # Setup .npmrc file to run npm update
      - uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'

      - name: 'build types, copy to types directory and commit'
        run: |
          git branch
          echo 'npm install and prepare'
          npm install
          npm run prepare
          echo 'copy files'
          cp -r lib/typescript/* neuroid-reactnative-sdk-types
          echo 'setup git config'
          git config --global user.email developer@neuro-id.com
          git config --global user.name neuroid-developer
          git add neuroid-reactnative-sdk-types
          set +e
          echo 'commit'
          git commit -m "update type definitions"
          echo 'push'
          git push --set-upstream origin
          set -e
