# ******************************************************************
# Merge "releases/**" PR to kick off the release to NPM registry.
# ******************************************************************

name: Auto publish to npm registry once release PR is merged

on:
  pull_request:
    branches:
      - main

env: 
  ACTION_URL: "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"

jobs:
  release:
    permissions:
      id-token: write  # Required for OIDC
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: '24'
          registry-url: 'https://registry.npmjs.org'

      - run: npm ci

      - run: NODE_AUTH_TOKEN="" npm publish --dry-run --access public --verbose

      - name: Upload npm publish logs
        uses: actions/upload-artifact@v4
        with:
            name: npm-publish-logs
            path: /home/runner/.npm/_logs/
