# ******************************************************************
# Merge "releases/**" PR to kick off the release to NPM registry.
# ******************************************************************

name: Auto publish to npm registry once release PR is merged

on:
  pull_request:
    branches:
      - main

env: 
  ACTION_URL: "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"

permissions:
  id-token: write   # Required for OIDC authentication
  contents: write   # Required for creating GitHub Release

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: '24'
          registry-url: 'https://registry.npmjs.org'

      - run: | 
          echo "CONFIG GET REGISTRY"  
          npm config get registry
      
          echo "CONFIG LIST"
          npm config list

      - run: npm install -g npm@latest

      # - run: npm ci

      - run: npm publish --dry-run --access public --verbose --provenance

      - name: Upload npm publish logs
        uses: actions/upload-artifact@v4
        with:
            name: npm-publish-logs
            path: /home/runner/.npm/_logs/
