name: Update Dev React Native iOS SDK

on:
  workflow_dispatch:
  repository_dispatch:
    types: [on-demand-testflight-dev]
  pull_request_target:
    types:
      - closed
    branches:
      - main

jobs:
  createTag:
    if: github.event_name == 'workflow_dispatch' || github.event_name == 'repository_dispatch' || github.event.pull_request.merged && !startsWith(github.head_ref, 'releases/')
    runs-on: ubuntu-latest
    steps:
      - name: Main branch Checkout
        uses: actions/checkout@v4

      - name: Update new commit to have "Development" Tag
        run: |
          git config --global user.email developer@neuro-id.com
          git config --global user.name neuroid-developer
          set +e
          git push origin :development
          git tag -d development
          git tag development
          git push origin development
          set -e

      - name: Run ReactNative Sandbox iOS Dev Deployment
        run: |
          curl \
          -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{ secrets.GPR_API_KEY }}" \
          https://api.github.com/repos/Neuro-ID/neuroid-reactnative-sdk-sandbox/dispatches \
          -d '{"event_type":"on-demand-testflight-dev","client_payload":{"version":"development", "message": "iOS development tag"}}'

      # - name: Send Slack Notification on Failure
      #   if: failure()
      #   uses: rtCamp/action-slack-notify@v2
      #   env:
      #     SLACK_CHANNEL: ${{ secrets.MOBILE_SLACK_NOTIFICATIONS_CHANNEL }}
      #     SLACK_COLOR: ${{ job.status }}
      #     SLACK_ICON: https://github.com/rtCamp.png?size=48
      #     SLACK_MESSAGE: 'Failed to trigger React Native iOS Sandbox release (Dev)'
      #     SLACK_TITLE: Failed to trigger React Native iOS Sandbox release (Dev)
      #     SLACK_USERNAME: rtBot
      #     SLACK_WEBHOOK: ${{ secrets.MOBILE_SLACK_WEBHOOK }}
