name: Update Dev React Native Android SDK
on:
  workflow_dispatch:
  repository_dispatch:
    types: [publish-dev-android]

jobs:
  refreshDependencies:
    name: Pull recent Android SDK master build
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true

      - name: Cache Gradle and wrapper
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant Permission for Gradlew to Execute
        run: chmod +x gradlew

      - name: Refresh dependencies
        run: ./gradlew :app:assemble --refresh-dependencies
  
  triggerRNSandboxDev:
    name: Trigger React Native Dev Sandbox release
    runs-on: ubuntu-latest
    needs: refreshDependencies
    steps:
      - name: Trigger ReactNative Sandbox Dev Deployment
        run: |
         curl \
             -X POST \
             -H "Accept: application/vnd.github.v3+json" \
             -H "Authorization: token ${{ secrets.GPR_API_KEY }}" \
             https://api.github.com/repos/Neuro-ID/neuroid-reactnative-sdk-sandbox/dispatches \
             -d '{"event_type":"publish-dev-android","client_payload":{"version":"master-SNAPSHOT", "message": "${{ github.event.commit.message }}"}}'

  notifications:
    runs-on: ubuntu-latest
    needs: triggerRNSandboxAndroidDev
    steps:
      - name: Send Slack Notification on Failure
        if: ${{ needs.refreshDependencies.result == 'failure' }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: ${{ secrets.MOBILE_SLACK_NOTIFICATIONS_CHANNEL }}
          SLACK_COLOR: ${{ job.status }}
          SLACK_ICON: https://github.com/rtCamp.png?size=48
          SLACK_MESSAGE: "Failed to trigger React Native Android Sandbox release (Dev)"
          SLACK_TITLE: Failed to trigger React Native Android Sandbox release (Dev)
          SLACK_USERNAME: rtBot
          SLACK_WEBHOOK: ${{ secrets.MOBILE_SLACK_WEBHOOK }}