name: Update Dev React Native Android SDK
on:
  workflow_dispatch:
  repository_dispatch:
    types: [publish-dev-android]
  pull_request_target:
    types:
      - closed
    branches:
      - main

jobs:
  createTag:
    name: Create Development tag
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Update new commit to have "Development" Tag
        run: |
          git config --global user.email developer@neuro-id.com
          git config --global user.name neuroid-developer
          set +e
          git push origin :development
          git tag -d development
          git tag development
          git push origin development
          set -e

  triggerRNSandboxAndroidDev:
    name: Trigger React Native Dev Sandbox release
    runs-on: ubuntu-latest
    needs: createTag
    steps:
      - name: Trigger ReactNative Sandbox Dev Deployment
        run: |
         curl \
             -X POST \
             -H "Accept: application/vnd.github.v3+json" \
             -H "Authorization: token ${{ secrets.GPR_API_KEY }}" \
             https://api.github.com/repos/Neuro-ID/neuroid-reactnative-sdk-sandbox/dispatches \
             -d '{"event_type":"publish-dev-android","client_payload":{"version":"master-SNAPSHOT", "message": "${{ github.event.commit.message }}"}}'

  notifications:
    runs-on: ubuntu-latest
    needs: triggerRNSandboxAndroidDev
    steps:
      - name: Send Slack Notification on Failure
        if: ${{ needs.triggerRNSandboxAndroidDev.result == 'failure' }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: ${{ secrets.MOBILE_SLACK_NOTIFICATIONS_CHANNEL }}
          SLACK_COLOR: ${{ job.status }}
          SLACK_ICON: https://github.com/rtCamp.png?size=48
          SLACK_MESSAGE: "Failed to trigger React Native Android Sandbox release (Dev)"
          SLACK_TITLE: Failed to trigger React Native Android Sandbox release (Dev)
          SLACK_USERNAME: rtBot
          SLACK_WEBHOOK: ${{ secrets.MOBILE_SLACK_WEBHOOK }}