name: SDK Version Update PR

on:
  workflow_dispatch:
    inputs:
      versionUpdate:
        description: >
          Choose the type of version update:            
          ** major: Cross platform breaking changes                                   
          ** minor: Cross platform minor changes                    
          ** patch: Changes affecting only this platform
        required: true
        default: 'patch'
        type: choice
        options:
          - major
          - minor
          - patch
      androidSdkVersion:
        description: 'Enter the NeuroID Android SDK version tag:'
        required: true
      iosSdkVersion:
        description: 'Enter the NeuroID iOS SDK version tag:'
        required: true

permissions:
  pull-requests: write
  contents: write

env:
  RELEASE_TYPE: ${{ github.event.inputs.versionUpdate }}
  IOS_SDK_VERSION: ${{ github.event.inputs.iosSdkVersion }}
  ANDROID_SDK_VERSION: ${{ github.event.inputs.androidSdkVersion }}

jobs:
  update_version:
    name: Update package version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Update version
        run: npm version ${{ env.RELEASE_TYPE }}

      - name: Read package version
        run: |
          PACKAGE_VERSION=$(node -p "require('./package.json').version")
          echo "PACKAGE_VERSION=${PACKAGE_VERSION}" >> $GITHUB_ENV
          echo "BRANCH_NAME=releases/${PACKAGE_VERSION}_version_update" >> $GITHUB_ENV

      - name: Update iOS / Android SDK version to latest release version
        run: |
          sed -i "s/:react-android-sdk:[0-9a-zA-Z.-]*/:react-android-sdk:${{ env.ANDROID_SDK_VERSION }}/g" android/build.gradle
          sed -i "s/.*'NeuroID', '\([^']*\)'.*/ s.dependency 'NeuroID', '${{ env.IOS_SDK_VERSION }}'/g" neuroid-reactnative-sdk.podspec

      - name: Commit version update
        run: |
          git config --global user.email developer@neuro-id.com
          git config --global user.name neuroid-developer   
          git checkout -b ${{ env.BRANCH_NAME }}
          git status
          git add package.json
          git add neuroid-reactnative-sdk.podspec
          git add package-lock.json
          git add android/build.gradle
          git commit -m "Update React native SDK to ${{ env.PACKAGE_VERSION }}"
          git push --set-upstream origin ${{ env.BRANCH_NAME }}

      - name: Open Pull Request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr create \
            --base main \
            --head ${{ env.BRANCH_NAME }} \
            --title "Update version for Release ${{ env.PACKAGE_VERSION }}" \
            --body "Update the SDK version to the \`${{ env.PACKAGE_VERSION }}\` release line."
